-keep class io.hengam.lib.notification.HengamNotification { *; }
-keep class io.hengam.lib.notification.UserNotification { *; }
-keep public interface io.hengam.lib.notification.HengamNotificationListener { *; }
-keep class io.hengam.lib.notification.NotificationData { *; }
-keep class io.hengam.lib.notification.NotificationButtonData { *; }
